#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# SWGS Pipeline (nextflow_tumwgs) documentation build configuration file.

# -- General configuration ------------------------------------------------

extensions = [
    'myst_parser',
    'sphinx.ext.autodoc',
]

# Support both RST and Markdown source files
source_suffix = ['.rst', '.md']

# Allow MyST to parse all Markdown heading levels as sections
myst_heading_anchors = 3

templates_path = ['_templates']

# The master toctree document.
master_doc = 'index'

project = 'SWGS Pipeline'
copyright = '2024, Clinical Genomics and Pathology, Skåne University Hospital'
author = 'Clinical Genomics and Pathology'

# Matches the pipeline version in nextflow.config
version = '3.0'
release = '3.0.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'SWGSPipelinedoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {}

latex_documents = [
    (master_doc, 'SWGSPipeline.tex', 'SWGS Pipeline Documentation',
     author, 'manual'),
]


# -- Options for manual page output ---------------------------------------

man_pages = [
    (master_doc, 'swgspipeline', 'SWGS Pipeline Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
    (master_doc, 'SWGSPipeline', 'SWGS Pipeline Documentation',
     author, 'SWGSPipeline',
     'Nextflow pipeline for somatic whole-genome sequencing analysis.',
     'Miscellaneous'),
]



