name: Build documentation

on:
  push:
    branches:
      - v2.0_production
    paths:
      - 'doc/**'
      - '.readthedocs.yml'
  pull_request:
    paths:
      - 'doc/**'
      - '.readthedocs.yml'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r doc/requirements.txt

      - name: Build Sphinx documentation
        run: sphinx-build -W --keep-going -b html doc doc/_build/html
